### ISSUE TITLE
Wie kann man die Influx-DB aufsetzen?

### ISSUE THREAD

**Issue by binderth** [Yikity2000/Fritzbox-Cable-to-Influx#1]
Hi!

bin gerade über deine coole Bibliothek gestolpert und finde exakt das, was ich rausfinden wollte: Wie sich mein Kabelanschluss gerade verhält.
Ich habe die [Modemwerte-1629979607692.json](https://github.com/Yikity2000/Fritzbox-Cable-to-Influx/blob/main/Modemwerte-1629979607692.json) einlesen können in mein Grafana. 
Kannst Du bitte auch die Influx-DB zum Import bereitstellen? Dann kann ich statt "maulberry" im Bash-Script dann einfach meine Influx-DB eintragen und alles sollte soweit laufen, denk ich?

wäre super!
Danke!
Thomas.

**Comment by Yikity2000** [comment]
Hallo Thomas,

 

Danke! 😊

 

in Zeile 145 musst du deine Influx Daten anpassen

curl -i -XPOST https://maulberry:8086/write?db=DOCSIS <https://maulberry:8086/write?db=DOCSIS&u=admin&p=xxx> &u=admin&p=xxx --insecure --data-binary @/tmp/modem.txt

 

Maulberry ist mein Server

DOCSIS heist die DB

U und P sollten klar sein

 

Und dann fließt alles in deine Datenbank.

 

Grüße

Koni

 

Von: Thomas B. ***@***.***> 
Gesendet: Sonntag, 19. März 2023 12:51
An: Yikity2000/Fritzbox-Cable-to-Influx ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [Yikity2000/Fritzbox-Cable-to-Influx] Wie kann man die Influx-DB aufsetzen? (Issue #1)

 

Hi!

bin gerade über deine coole Bibliothek gestolpert und finde exakt das, was ich rausfinden wollte: Wie sich mein Kabelanschluss gerade verhält.
Ich habe die Modemwerte-1629979607692.json <https://github.com/Yikity2000/Fritzbox-Cable-to-Influx/blob/main/Modemwerte-1629979607692.json>  einlesen können in mein Grafana.
Kannst Du bitte auch die Influx-DB zum Import bereitstellen? Dann kann ich statt "maulberry" im Bash-Script dann einfach meine Influx-DB eintragen und alles sollte soweit laufen, denk ich?

wäre super!
Danke!
Thomas.

**Comment by Yikity2000** [comment]
und http oder HTTPS ist auch wichtig!

 

Von: Thomas B. ***@***.***> 
Gesendet: Sonntag, 19. März 2023 12:51
An: Yikity2000/Fritzbox-Cable-to-Influx ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [Yikity2000/Fritzbox-Cable-to-Influx] Wie kann man die Influx-DB aufsetzen? (Issue #1)

 

Hi!

bin gerade über deine coole Bibliothek gestolpert und finde exakt das, was ich rausfinden wollte: Wie sich mein Kabelanschluss gerade verhält.
Ich habe die Modemwerte-1629979607692.json <https://github.com/Yikity2000/Fritzbox-Cable-to-Influx/blob/main/Modemwerte-1629979607692.json>  einlesen können in mein Grafana.
Kannst Du bitte auch die Influx-DB zum Import bereitstellen? Dann kann ich statt "maulberry" im Bash-Script dann einfach meine Influx-DB eintragen und alles sollte soweit laufen, denk ich?

wäre super!
Danke!
Thomas.

**Comment by binderth** [comment]
Hi Koni,

super! Danke für die Unterstützung. Die Daten fliessen jetzt rein, _ich hatte wohl das Problem, dass ich eine 2.6.1 Version der Influx-DB und eine 9.4.3 Version von Grafana verwende. Die API für influxdb ist nun /v2 und erlaubt das simple write nur noch mit einem Pattern. die /v2 geht auch ohne._ 

Wichtig ist auch noch, dass man für die Datenquelle im Grafana dann die InfluxQL verwendet! ;)

Danke nochmal für Deine Unterstützung, ich kann jetzt dann immerhin erkennen, wann mein Upstream vin 64QAM auf 4QAM droppt und den ganzen Rest!
